library(sleuth)
stab <- read.table("sample_table.txt",header=TRUE,stringsAsFactors=FALSE)
so <- sleuth_prep(stab)
so <- sleuth_fit(so, ~condition, 'full')
so <- sleuth_fit(so, ~1, 'reduced')
so <- sleuth_lrt(so, 'reduced', 'full')
library(dplyr)
sleuth_table <- sleuth_results(so, 'reduced:full', 'lrt', show_all = FALSE)
sleuth_significant <- dplyr::filter(sleuth_table, qval <= 0.05) %>% dplyr::arrange(pval)
sleuth_significant <- dplyr::select(sleuth_significant, target_id,test_stat, pval, qval)
write.table(sleuth_significant, file="DEGs.txt",quote = FALSE,row.names = FALSE)
